apiVersion: apps/v1
kind: Deployment
metadata:
  name: wetty-deploy
  labels:
    app: wetty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wetty
  template:
    metadata:
      labels:
        app: wetty
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: wetty-data-pvc
      containers:
      - name: wetty 
        image: wettyoss/wetty
        stdin: true
        tty: true
        args: ["--base", "/"]
        volumeMounts:
          - name: data
            mountPath: "/home"
        ports:
        - name: listen
          protocol: TCP
          containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: wetty-service
spec:
  selector:
    app: wetty
  ports:
    - protocol: TCP
      name: wetty
      targetPort: 3000
      port: 3000
