apiVersion: apps/v1
kind: Deployment
metadata:
  name: gogs-deploy
  labels:
    app: gogs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gogs
  template:
    metadata:
      labels:
        app: gogs
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: gogs-data-pvc
      containers:
      - name: gogs 
        image: gogs/gogs
        stdin: true
        tty: true
        volumeMounts:
          - name: data
            mountPath: "/data"
        ports:
        - name: web
          protocol: TCP
          containerPort: 3000
        - name: ssh
          protocol: TCP
          containerPort: 22
---
apiVersion: v1
kind: Service
metadata:
  name: gogs-service
spec:
  selector:
    app: gogs
  ports:
    - protocol: TCP
      name: gogs
      targetPort: 3000
      port: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: gogs-ssh
spec:
  type: NodePort
  selector:
    app: gogs
  ports:
    - protocol: TCP
      name: ssh
      nodePort: 10022
      port: 22
