apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gogs-data-pvc 
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
