apiVersion: apps/v1
kind: Deployment
metadata:
  name: brook-deploy
  labels:
    app: brook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brook
  template:
    metadata:
      labels:
        app: brook
    spec:
      volumes:
        - name: code
          configMap:
            name: brook-entry
      containers:
      - name: brook 
        image: alpine
        stdin: true
        tty: true
        workingDir: /app
        command: ["/bin/sh", "/app/entry.sh"]
        env:
        - name: PASSWORD
          value: "brook链接密码"
        volumeMounts:
          - name: code
            mountPath: "/app"
            readOnly: false
        ports:
        - name: listen
          protocol: TCP
          containerPort: 9999
---
apiVersion: v1
kind: Service
metadata:
  name: brook-service
spec:
  selector:
    app: brook
  ports:
    - protocol: TCP
      name: brook
      targetPort: 9999
      port: 9999
