apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy-entry-deploy
  labels:
    app: caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      volumes:
        - name: caddyfile
          configMap:
            name: caddyfile
      containers:
      - name: caddy
        image: caddy:2-alpine
        stdin: true
        tty: true
        volumeMounts:
          - name: caddyfile
            mountPath: "/etc/caddy"
            readOnly: false
        ports:
        - name: http
          protocol: TCP
          containerPort: 80
        - name: https 
          protocol: TCP
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: caddy-service
spec:
  type: NodePort
  selector:
    app: caddy
  ports:
    - protocol: TCP
      name: http
      nodePort: 80
      port: 80
    - protocol: TCP
      name: https
      nodePort: 443
      port: 443
